version: 100

window:
  title: "Default Project Name"
  width: 2000
  height: 800
  fullscreen: false

vulkan:
  instance:
    app_name: "Default App Name"
    app_version: 0
    engine_name: "Daybreak Engine"
    engine_version: 0
    api_version: [0, 1, 0]
  physical_device:
    desired_queue_flags:
      graphics: true
      compute: false
      transfer: false
      sparse: false
    desired_device_features: 
      geometry_shader: false


