version: 100

window:
  title: "Default Project Name"
  width: 800
  height: 600
  fullscreen: false

vulkan:
  instance:
    app_name: "Default App Name"
    app_version: 0
    engine_name: "Daybreak Engine"
    engine_version: 0
    api_version: [0, 1, 0]