name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: build - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
#         os: [windows-latest, ubuntu-latest, macos-latest]
        os: [windows-latest]
        include:
#           - os: ubuntu-latest
#             target: Linux
#           - os: macos-latest
#             target: Macos
          - os: windows-latest
            target: Windows
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
#     - name: Run tests
#       run: cargo test --verbose
